# Generated by Django 5.1.dev20240318084533 on 2024-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField()),
                ('race_name', models.CharField(max_length=30)),
                ('race_distance', models.IntegerField(default=0)),
                ('ground', models.CharField(choices=[('grass', '芝'), ('dirt', 'ダート')], max_length=5)),
            ],
        ),
    ]
