# Generated by Django 5.1.dev20240318084533 on 2024-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='race',
            name='ground',
            field=models.CharField(choices=[('grass', '芝'), ('dirt', 'ダート')], max_length=5, verbose_name='馬場情報'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(verbose_name='レース日時'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_distance',
            field=models.IntegerField(default=0, verbose_name='レース距離'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(max_length=30, verbose_name='レース名'),
        ),
    ]
