# Generated by Django 5.1.dev20240318084533 on 2024-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0003_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='説明'),
        ),
    ]
