# Generated by Django 5.1.dev20240318084533 on 2024-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0006_remove_race_ground'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ground',
            field=models.CharField(choices=[('grass', '芝'), ('dirt', 'ダート')], default='grass', max_length=5, verbose_name='馬場情報'),
        ),
    ]
